name: music_library
description: "Flutter Music Library - 50k+ track virtualization with BLoC pattern"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  equatable: ^2.0.7
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
